ALTER TABLE test_users
  ADD COLUMN IF NOT EXISTS first_name    TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS last_name     TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS phone         TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS address       TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS registered_in JSONB NOT NULL DEFAULT '[]';
